BGA should be done by now, reorganized some more things, tweaked scripts

diff --git a/makerd b/makerd
--- a/makerd
+++ b/makerd
@@ -1,7 +1,37 @@
 #!/bin/bash
+
 if [[ ! -e ramdisk/bin/mkrd ]]; then
-  pushd ramdisk
-  make
-  popd
+  pushd ramdisk >/dev/null
+  echo -n "building mkrd... "
+  make >/dev/null
+  if [ $? != 0 ]; then
+    echo "error"
+    exit 1
+  else
+    echo "done"
+  fi
+  popd >/dev/null
 fi
-ramdisk/bin/mkrd initramfs-aliceos.img rdcontents/*
+
+mkdir -p rdtemp
+pushd rdtemp >/dev/null
+echo -n "extracting rdcontents... "
+tar xf ../rdcontents.tar.xz
+if [ $? != 0 ]; then
+  echo "error"
+  exit 1
+else
+  echo "done"
+fi
+popd >/dev/null
+
+echo -n "creating ramdisk... "
+ramdisk/bin/mkrd initramfs-aliceos.img rdtemp/*
+if [ $? != 0 ]; then
+  echo "error"
+  exit 1
+else
+  echo "done"
+fi
+
+rm -rf rdtemp
diff --git a/run_aliceos b/run_aliceos
--- a/run_aliceos
+++ b/run_aliceos
@@ -1,10 +1,24 @@
 #!/bin/bash
-if [[ ! -e initramfs-aliceos.img ]]; then
-  echo "you haven't created an initial ramdisk"
-else
-  if [[ ! -n $* ]]; then
-    qemu-system-i386 -kernel vmaliceos -serial stdio -vga std -initrd initramfs-aliceos.img
+
+if [[ ! -e vmaliceos ]]; then
+  echo -n "building aliceos kernel... "
+  make >/dev/null
+  if [ $? != 0 ]; then
+    echo "error"
+    exit 1
   else
-    qemu-system-i386 -kernel vmaliceos -serial stdio -vga std -initrd initramfs-aliceos.img -append "$@"
+    echo "done"
   fi
+fi
+
+if [[ ! -e initramfs-aliceos.img ]]; then
+  ./makerd
+fi
+
+if [[ ! -n $* ]]; then
+  echo "running aliceos with no commandline"
+  qemu-system-i386 -kernel vmaliceos -serial stdio -vga std -initrd initramfs-aliceos.img
+else
+  echo "running aliceos with commandline \"$@\""
+  qemu-system-i386 -kernel vmaliceos -serial stdio -vga std -initrd initramfs-aliceos.img -append "$@"
 fi
